<?= $this->doctype() ?>

<html lang="ja">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Site Mockup by ZF3')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('site-top') ?>">
                        Site Mockup
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                      <?php if (isset($identity) && $identity): ?>
                        <li <?= (isset($this->navPosition) && $this->navPosition === 'contents') ? 'class="active"':'' ?>>
                          <a href="<?= $this->url('site-top', ['action'=>'contents']) ?>">Contents</a>
                        </li>
                        <li><a href="<?= $this->url('site-top', ['action'=>'logout']) ?>">Logout</a></li>
                      <?php elseif (isset($this->navPosition) && $this->navPosition !== 'site-login'): ?>
                        <li><a href="<?= $this->url('site-login') ?>">Loin</a></li>
                      <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger()
                    ->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times:</button>')
                    ->setMessageSeparatorString('<br />')
                    ->setMessageCloseString('</div>');
            ?>
            <?php
                echo $flash->render('error',
                    array('alert', 'alert-dismissable', 'alert-danger')
                );
            ?>
            <?php
                echo $flash->render('info',
                    array('alert', 'alert-dismissable', 'alert-info')
                );
            ?>
            <?php
                echo $flash->render('default',
                    array('alert', 'alert-dismissable', 'alert-warning')
                );
            ?>
            <?php
                echo $flash->render('success',
                    array('alert', 'alert-dismissable', 'alert-success')
                );
            ?>
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>